parameters:
    - name: environment
      type: string
      default: master
      values:
          - master
          - qa
          - prod
    - name: reference
      default: refs/heads/master
      type: string
      values:
          - refs/heads/master
          - refs/heads/qa
          - refs/heads/prod
    - name: Artifactname
      type: string
      default: Dev-Artifact
      values:
        - Dev-Artifact
        - Qa-Artifact
        - Prod-Artifact

variables:
 - name: environments
   value: ${{parameters.environment}}

resources:
 repositories:
   - repository: dotnetapp
     type: git
     name: Abdul/dotnetapp
     ref: ${{parameters.reference}}

trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: build
  displayName: build application
  jobs:
    - template: ../build-template.yaml
      parameters:
        versionsdk: $(versionsdk)
        ArtifactName: ${{parameters.Artifactname}}
        projectssln: $(projectssln)
        build: $(build)
        Publish: $(publish)
        Restore: $(restore)

- stage: DeployToDev
  displayName: Deploying to dev 
  dependsOn: build
  condition: and(succeeded(), eq(variables['environments'], 'master'))
  jobs: 
  - template: ../Dev-deploy-template.yaml
    parameters:
      ArtifactName: ${{parameters.Artifactname}}
      AzureSubscription: $(AzureSubscription)
      WebAppName: $(WebAppName)

- stage: DeployToQA
  displayName: Deploying to QA
  dependsOn: build
  condition: and(succeeded(), eq(variables['environments'], 'qa'))
  jobs: 
  - template: ../QA-deploy-template.yaml
    parameters:
      ArtifactName: ${{parameters.Artifactname}}
      AzureSubscription: $(AzureSubscription)
      WebAppNameQA: $(WebAppNameQA)

- stage: DeployToProd
  displayName: Deploying to Prod
  dependsOn: build
  condition: and(succeeded(), eq(variables['environments'], 'Prod'))
  jobs: 
  - template: ../PROD-deploy-template.yaml
    parameters:
      ArtifactName: ${{parameters.Artifactname}}
      AzureSubscription: $(AzureSubscription)
      WebAppNameProd: $(WebAppNameProd)