trigger:
 - none

pool:
  vmImage: 'windows-latest' 

steps:
 - task: AzureCLI@2
   inputs:
     azureSubscription: 'Free Trial(ceb39d96-d470-4cf0-8f91-0de61b98d924)'
     scriptType: 'ps'
     scriptLocation: 'inlineScript'
     inlineScript: |
       Invoke-RestMethod http://ipinfo.io/json | Select -exp ip
       azcopy --version
 - task: DownloadSecureFile@1
   inputs:
     secureFile: 'ip.txt'
 - task: PowerShell@2
   inputs:
     targetType: 'inline'
     script: 'cat $(Agent.TempDirectory)/ip.txt'
  
 