parameters:
  - name: NodeToolVersion
    default: 16.x
  - name: ArtifactName
    type: string
    default: AngularApp
  
jobs:
  - job: build
    displayName: Build Angular App
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: syncgitEshopCommerce
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            powershell.exe D:\a\1\s\HomeMove.ps1
            powershell.exe D:\a\1\s\Angular_DotNET_Projects\ScriptsPS\CopyScriptPStoWorkingDir.ps1
            powershell.exe D:\a\1\s\ScriptsPS\MoveFilesToPWDAngular.ps1
            powershell.exe D:\a\1\s\ScriptsPS\ReplaceServiceUrl.ps1
            ls
      - task: NodeTool@0
        inputs:
          versionSpec: ${{parameters.NodeToolVersion}}
        displayName: 'Install Node.js 16.x'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            npm install
            npm i angular-responsive-carousel --force
            npm install eslint
            npm install webpack
            npm run build
          workingDirectory: '$(System.DefaultWorkingDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            powershell.exe D:\a\1\s\ScriptsPS\webCofig.ps1
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/eshop-app'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        displayName: 'Archive Build Artifacts'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: ${{parameters.ArtifactName}}
          publishLocation: 'Container'