parameters:
  - name: AzureSubscription
    default: 'app-service-connection'
  - name: WebAppName
    type: string
    default: 'dev-angular-app'
  - name: ArtifactName
    default: dot-net-app
  - name: WebAppNameQA
    type: string
    default: 'QA-eshopcommerce'
jobs:
 - job: deployDev
   steps:
     - task: DownloadBuildArtifacts@1
       inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: ${{parameters.ArtifactName}}
        downloadPath: '$(System.ArtifactsDirectory)'
     - task: AzureRmWebAppDeployment@4
       inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: ${{parameters.AzureSubscription}}
        appType: 'webApp'
        WebAppName: ${{parameters.WebAppName}}
        packageForLinux: '$(System.ArtifactsDirectory)/${{parameters.ArtifactName}}/*.zip'