jobs:
  - job: Build
    displayName: Build job
    variables:
      - template: variables.yml
    steps:
      - checkout: React-App
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'
      
      - script: |
          npm install -g @angular/cli
          npm install
          npm run build
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        displayName: 'Archive Build Artifacts'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: $(ArtifactName)
          publishLocation: 'Container'
