jobs:
- job: Build
  displayName: Build job
  variables:
    - template: variables.yml
  steps:
    - checkout: React-App
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js 16.x'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          npm install
          npm install eslint
          npm install webpack
          npm run build
        workingDirectory: '$(System.DefaultWorkingDirectory)'
 
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)\build'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Archive Build Artifacts'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: $(ArtifactName)
        publishLocation: 'Container'
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # install modules 
          Install-PackageProvider -Name NuGet -Force -Scope AllUsers
          Install-Module -Name PackageManagement -Scope AllUsers -Force -AllowClobber
          Install-Module -Name PowerShellGet -Scope AllUsers -Force -AllowClobber
          Install-Module -Name Az -Scope CurrentUser -Force -Allowclobber
          powershell.exe $(System.DefaultWorkingDirectory)\artifactsinstoarge.ps1
          Write-Host "Successfully Uploaded Artifact into storage account"
  
  


